name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for pushing to gh-pages
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for peaceiris/actions-gh-pages

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create environment files
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir -p src/app/environments
          cat > src/app/environments/environment.prod.ts <<EOF
          export const environment = {
            production: true,
            github: {
              api: 'https://api.github.com',
              repo: 'nurekowser01/NWPGCL_Drawing',
              token: '${GH_TOKEN}'
            }
          };
          EOF
          # Verify file was created
          ls -la src/app/environments/

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /NWPGCL_Drawing/

      - name: Add .nojekyll file
        run: touch dist/power-plant-drawing-app/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser