name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Create environment files (correct path)
        run: |
          # Create the exact path your app expects
          mkdir -p src/environments
          
          # Development environment
          echo "export const environment = { 
            production: false, 
            github: { 
              api: 'https://api.github.com', 
              repo: 'nurekowser01/NWPGCL_Drawing', 
              token: '' 
            } 
          };" > src/environments/environment.ts
          
          # Production environment with secure token injection
          echo "export const environment = { 
            production: true, 
            github: { 
              api: 'https://api.github.com', 
              repo: 'nurekowser01/NWPGCL_Drawing', 
              token: '${{ secrets.GH_TOKEN }}' 
            } 
          };" > src/environments/environment.prod.ts
          
          # Verify
          echo "Environment files created at:"
          ls -la src/environments/
          echo "Token ending: ${{ secrets.GH_TOKEN }}"

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href /NWPGCL_Drawing/

      - name: Add .nojekyll file
        run: touch dist/power-plant-drawing-app/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser