name: Deploy to GitHub Pages

on:
  push:
    branches: [main-1]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Configure production environment
        run: |
          # Ensure production environment is properly set
          echo "export const environment = { production: true };" > src/environments/environment.prod.ts
          cat src/environments/environment.prod.ts

      - name: Build Angular (Production)
        run: |
          npm run build -- --configuration production \
            --base-href /NWPGCL_Drawing/ \
            --output-hashing=all

      

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser