name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare environment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Create production environment file
          cp src/environments/environment.prod.template.ts src/environments/environment.prod.ts
          sed -i "s/##GITHUB_TOKEN##/$GH_TOKEN/g" src/environments/environment.prod.ts
          echo "Environment file prepared"

      - name: Build Angular app
        run: |
          npm run build -- --configuration production --base-href /NWPGCL_Drawing/ --output-hashing=all

      - name: Cleanup
        run: rm src/environments/environment.prod.ts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser