name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Inject secrets directly into index.html
          sed -i '/<\/title>/a \
          <script>\
            window.GITHUB_API = "https://api.github.com";\
            window.GITHUB_REPO = "nurekowser01/NWPGCL_Drawing";\
            window.GITHUB_TOKEN = "'"$GH_TOKEN"'";\
          </script>' src/index.html
          
          npm run build -- --configuration production --base-href /NWPGCL_Drawing/

      - name: Add .nojekyll file
        run: touch dist/power-plant-drawing-app/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser