name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # Runs when you push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          echo "export const environment = { production: true, github: { api: 'https://api.github.com', repo: 'nurekowser01/NWPGCL_Drawing', token: '${{ secrets.GH_TOKEN }}' } };" > src/environments/environment.prod.ts
          npm run build -- --configuration production --base-href /NWPGCL_Drawing/

      - name: Add .nojekyll file
        run: touch dist/power-plant-drawing-app/browser/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/power-plant-drawing-app/browser